name: 'Build'

on:
  push:
    branches:
      - rollup
  pull_request:
    branches:
      - rollup

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm install
          npm run build
